[package]
name = "skia-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glfw = "0.53.0"
skia-safe = { version = "0.67.0", features = ["gl", "textlayout"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
winit = "0.29.2"
async-tungstenite = { version = "0.23.0", features = ["async-std-runtime"] }
async-std = "1.12.0"
anyhow = "1.0.72"
futures = "0.3.28"
ws-protocol = { path = "../ws-protocol" }
attohttpc = "0.26.1"
rand = "0.8.5"
byteorder = "1.5.0"
