[package]
name = "amll-lyric"
version = "0.2.2"
authors = ["SteveXMH <39523898+Steve-xmh@users.noreply.github.com>"]
edition = "2021"
repository = "https://github.com/Steve-xmh/applemusic-like-lyrics"
description = "一个歌词解析/生成模块，着重于歌词内容解析，支持多种格式"
license = "GPL-3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = [
    "ass",
    "lrc",
    "yrc",
    "qrc",
    "lys",
    "eslrc",
    "ttml",
    "eqrc",
    "serde",
]
ass = []
lrc = ["dep:nom"]
yrc = ["dep:nom"]
qrc = ["dep:nom"]
lys = ["dep:nom"]
eslrc = ["dep:nom", "lrc"]
ttml = ["dep:quick-xml", "dep:thiserror", "dep:nom"]
eqrc = ["dep:miniz_oxide", "dep:cc"]
serde = ["dep:serde"]

[dependencies]
nom = { version = "7.1", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
cipher = { version = "0.4", optional = true }
miniz_oxide = { version = "0.7", optional = true }
quick-xml = { version = "0.31", optional = true }
thiserror = { version = "1", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2" }
serde-wasm-bindgen = { version = "0.6" }
console_error_panic_hook = { version = "0.1", optional = true }
wee_alloc = { version = "0.4", optional = true }
js-sys = { version = "0.3", optional = true }

[build-dependencies]
cc = { version = "1.0", optional = true }
