name: "构建并部署开发文档"

on: push

jobs:
  deploy-docs:
    name: 构建并部署开发文档
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: 克隆仓库
      - name: 安装 wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest
      - name: 安装 wasm32 目标
        run: rustup target add wasm32-unknown-unknown
      - name: 安装依赖并构建网站
        run: |
          yarn
          yarn workspace @applemusic-like-lyrics/docs build
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
          AMLL_GITHUB_IS_ACTION: true
      - name: 部署到 Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/docs/out
