[package]
name = "fft"
version = "0.1.0"
authors = ["SteveXMH <39523898+Steve-xmh@users.noreply.github.com>"]
edition = "2021"
repository = "https://github.com/Steve-xmh/applemusic-like-lyrics"
description = "一个音频可视化模块，用于将传入的音频原始波形数据转换成便于观赏显示的频谱"
license = "GPL-3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook", "wee_alloc"]

[dependencies]
wasm-bindgen = "0.2"
arrayvec = "^0.7"
spectrum-analyzer = "1.5"
symphonia-core = "^0.5"
rubato = "^0.14"
instant = { version = "0.1", features = [ "wasm-bindgen" ] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4", optional = true }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
